// <auto-generated />
using System;
using EstacionERP.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstacionERP.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(EstacionDbContext))]
    [Migration("20260924180458_ImpresionComprobantes")]
    partial class ImpresionComprobantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("LimiteCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TieneCuentaCorriente")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RazonSocial");

                    b.HasIndex("TipoDocumento", "NumeroDocumento");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CondicionIva = 5,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimiteCredito = 0m,
                            NumeroDocumento = "0",
                            RazonSocial = "CONSUMIDOR FINAL",
                            TieneCuentaCorriente = false,
                            TipoDocumento = 99
                        });
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cae")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime?>("CaeVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComprobanteAsociadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Concepto")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Entorno")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaServicioDesde")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaServicioHasta")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaVencimientoPago")
                        .HasColumnType("date");

                    b.Property<decimal>("ImporteExento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteNoGravado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteTributos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("MensajesArca")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumeroIntentado")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntoVentaId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntoVentaNumero")
                        .HasColumnType("integer");

                    b.Property<int>("ReceptorCondicionIva")
                        .HasColumnType("integer");

                    b.Property<string>("ReceptorDomicilio")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReceptorNumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("ReceptorRazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ReceptorTipoDocumento")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadNegocioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ComprobanteAsociadoId");

                    b.HasIndex("Estado");

                    b.HasIndex("Fecha");

                    b.HasIndex("PuntoVentaId");

                    b.HasIndex("UnidadNegocioId");

                    b.HasIndex("Entorno", "PuntoVentaNumero", "Tipo", "Numero")
                        .IsUnique();

                    b.ToTable("comprobantes", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.ComprobanteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlicuotaIva")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ComprobanteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsServicio")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ImporteIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComprobanteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("comprobantes_items", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.ComprobanteIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlicuotaIva")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseImponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ComprobanteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComprobanteId");

                    b.ToTable("comprobantes_iva", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.ConfiguracionFiscal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AliasCertificado")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CertificadoPem")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CertificadoVence")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClavePendientePem")
                        .HasColumnType("text");

                    b.Property<string>("ClavePrivadaPem")
                        .HasColumnType("text");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Entorno")
                        .HasColumnType("integer");

                    b.Property<string>("IngresosBrutos")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("InicioActividades")
                        .HasColumnType("date");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SolicitudCertificadoPem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("configuracion_fiscal", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AlicuotaIva")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CodigoFabricante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ControlaStock")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Marca")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Rubro")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadNegocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("Descripcion");

                    b.HasIndex("UnidadNegocioId", "Codigo")
                        .IsUnique();

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.PuntoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("FormatoImpresion")
                        .HasColumnType("integer");

                    b.Property<string>("Impresora")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ImprimirAlEmitir")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadNegocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("UnidadNegocioId");

                    b.ToTable("puntos_venta", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.TicketAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Entorno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Expira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Servicio", "Entorno", "Cuit")
                        .IsUnique();

                    b.ToTable("tickets_acceso_arca", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.UnidadNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("unidades_negocio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Codigo = "PLAYA",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Playa / Combustibles"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Codigo = "REPUESTOS",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Repuestos"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Codigo = "LAVADERO",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Lavadero"
                        });
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DebeCambiarPassword = true,
                            NombreCompleto = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "PBKDF2-SHA256$100000$RXN0YWNpb25FUlAtaW5pIQ==$J7LlGFrH/7nIgI0D8uEdmGpPEaBTmMFwA8RH6gPGL9s=",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.UsuarioUnidadNegocio", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadNegocioId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "UnidadNegocioId");

                    b.HasIndex("UnidadNegocioId");

                    b.ToTable("usuarios_unidades_negocio", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Comprobante", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstacionERP.Domain.Entidades.Comprobante", "ComprobanteAsociado")
                        .WithMany()
                        .HasForeignKey("ComprobanteAsociadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EstacionERP.Domain.Entidades.PuntoVenta", "PuntoVenta")
                        .WithMany()
                        .HasForeignKey("PuntoVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstacionERP.Domain.Entidades.UnidadNegocio", "UnidadNegocio")
                        .WithMany()
                        .HasForeignKey("UnidadNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ComprobanteAsociado");

                    b.Navigation("PuntoVenta");

                    b.Navigation("UnidadNegocio");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.ComprobanteItem", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.Comprobante", null)
                        .WithMany("Items")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstacionERP.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.ComprobanteIva", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.Comprobante", null)
                        .WithMany("Alicuotas")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Producto", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.UnidadNegocio", "UnidadNegocio")
                        .WithMany()
                        .HasForeignKey("UnidadNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadNegocio");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.PuntoVenta", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.UnidadNegocio", "UnidadNegocio")
                        .WithMany("PuntosVenta")
                        .HasForeignKey("UnidadNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadNegocio");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.UsuarioUnidadNegocio", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.UnidadNegocio", "UnidadNegocio")
                        .WithMany()
                        .HasForeignKey("UnidadNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstacionERP.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Unidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadNegocio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Vehiculo", b =>
                {
                    b.HasOne("EstacionERP.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Comprobante", b =>
                {
                    b.Navigation("Alicuotas");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.UnidadNegocio", b =>
                {
                    b.Navigation("PuntosVenta");
                });

            modelBuilder.Entity("EstacionERP.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
